# Dockerfile.backend

FROM python:3.9-slim

WORKDIR /app

COPY backend_main.py /app
COPY data.csv /app

RUN pip install fastapi[all] pandas

EXPOSE 8000

CMD ["uvicorn", "backend_main:app", "--host", "0.0.0.0", "--port", "8000"]
