# Dockerfile for FastAPI
FROM python:3.9-slim

WORKDIR /app

COPY main.py .
COPY ENB2012_data.csv . 
RUN pip install fastapi uvicorn pandas numpy

EXPOSE 8000
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
