# Dockerfile for Streamlit
FROM python:3.9-slim

WORKDIR /app

COPY app.py .
COPY ENB2012_data.csv .

RUN pip install streamlit pandas requests

EXPOSE 8501
CMD ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0"]
