FROM python:3.9-slim

WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    libatlas-base-dev \
    && rm -rf /var/lib/apt/lists/*

RUN python -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

COPY requirements_pandas.txt .

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements_pandas.txt

COPY . .

CMD ["python", "app.py"]